Metrics:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignParameters:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpecialGlobalVars:
  Enabled: false
